### ISSUE TITLE
Grading

### ISSUE THREAD

**Issue by SvenNekula** [SvenNekula/newproject#10]
Hey @maxheld83 ,

unfortunately I've been pretty swamped lately due to work and university, so I didn't really have the time to work on this project more.
Last thing I did was fix the error messages. 
Anyway I think this is ready to be graded. 
Thanks again for the packages you listed in #9 ! I've looked into all of them, but couldn't get any cool things running yet. I'll experiment using them in summer again though, after graduating from the FAU. 
So let me know if there's anything you notice during grading that I should absolutely change etc.

Thanks in advance!

(Edited because I forgot to tag you.. oops!)

**Comment by maxheld83** [comment]
done!
