### ISSUE TITLE
remove github dependency on lwgeom

### ISSUE THREAD

**Issue by maxheld83** [SvenNekula/newproject#5]
setting up the CI in #4 was a bit of a headache, because CRAN-{lwgeom} currently cannot be installed from source on Ubuntu as per https://github.com/r-spatial/lwgeom/issues/28, because some system dependency isn't properly configured.

I remedied this by installing the version off of GitHub which is more recent and apparently has fixed the problem.

But this is usually not a good idea long term and may break.

So it's a good idea to either 

1. delete the dependency alltogether, 
2. or wait until the new version is on CRAN and then remote this bit from `DESCRIPTION`:

```
Remotes:
    r-spatial/lwgeom@b80842e23fdbc150ee8746b2aad86cc84dd10a60
```

Also, it appears that you're not actually directly using {lwgeom}, but that some package depends on it in turn.
I couldn't figure out which that was, so you'd have to remove that for 1.

**Comment by SvenNekula** [comment]
Oh Lord, I'm sorry for all the hassle.. 
I'll look into fixing that tomorrow / the next few days. 
Thanks a lot for the help though!!

**Comment by maxheld83** [comment]
no problem, this always happens.
It's kind of a dirty secret how much of this kind of work is just debugging system dependencies 😼.

**Comment by SvenNekula** [comment]
I think I could have saved you a lot of time by just doing what I did at #8 
Are you fine with that? I just rendered the animation locally, saved it as gif, and embedded it in markdown.
