### ISSUE TITLE
add github personal access token

### ISSUE THREAD

**Issue by maxheld83** [SvenNekula/newproject#7]
I think the deploy to your webpage isn't currently working because you still need to assign a GitHub Personal Access Token.

To do that:
- create a PAT: https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line
- copy/paste to PAT to your repo settings/secrets, and there paste it under the name `GH_PAT`.
- then commit again something

**Comment by SvenNekula** [comment]
Thanks!
